### ISSUE TITLE
blockchain.estimatefee doesn't work for Bitcoin Cash

### ISSUE THREAD

**Issue by david4neblio** [Electron-Cash/electrumx#18]
See this GitHub issue for reference: https://github.com/kyuupichan/electrumx/issues/845

Bitcoin Cash has removed estimatesmartfee (https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/release-notes/release-notes-0.17.2.md)

Bitcoin Cash still has estimatefee but returns error upon being provided arguments. It requests calling estimatefee without arguments. ElectrumX protocol requires blockchain.estimatefee to have arguments.

Based on this code in the codebase:
```
    async def estimatefee(self, block_count):
        '''Return the fee estimate for the block count.  Units are whole
        currency units per KB, e.g. 0.00000995, or -1 if no estimate
        is available.
        '''
        args = (block_count, )
        if await self._is_rpc_available('estimatesmartfee'):
            estimate = await self._send_single('estimatesmartfee', args)
            return estimate.get('feerate', -1)
        return await self._send_single('estimatefee', args)
```
Although the Electrum server will default to estimatefee if estimatesmartfee doesn't exist, it is not possible to call estimatefee without an argument.

This fork of the Electrum server should be adjusted accordingly to match the RPC response. Preferably by ignoring the arguments sent to it from Electrum clients and returning the result of estimatefee without arguments.

**Comment by cculianu** [comment]
Ah, I was not aware of this change.  `estimatefee` is a pretty useless call on Bitcoin Cash.  We may take it out altogether and always just return some default hard-coded value of 1.0 sats/B.

Thanks for notifying us of this. I will modify ElectronX to do something besides return error (whether it be return a hard-coded value or just return whatever bitcoind says).

**Comment by cculianu** [comment]
I am closing this thread because this fork has been discontinued.  This has been fixed in Fulcrum server as well as ElectrumX.  See issue #20 .
